BEGIN TRANSACTION;
CREATE TABLE `VENUES` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Town`	INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE `TOWNS` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE
);
CREATE TABLE "THEMES" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE
);
CREATE TABLE `SPEAKERS` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE
);
CREATE TABLE `SERMONS` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`SERIES`	INTEGER NOT NULL DEFAULT 0,
	`DateCreated`	TEXT NOT NULL,
	`Venue`	INTEGER NOT NULL DEFAULT 0,
	`Town`	INTEGER NOT NULL DEFAULT 0,
	`Activity`	INTEGER NOT NULL DEFAULT 0,
	`Speaker`	INTEGER NOT NULL DEFAULT 0,
	`Theme`		INTEGER NOT NULL DEFAULT 0,
	`Title`	TEXT NOT NULL,
	`Text`	TEXT,
	`Hymn`	TEXT,
	`Content`	TEXT NOT NULL
);
CREATE TABLE `SERIESSPEAKERS` (
	`SeriesId`	INTEGER NOT NULL,
	`SpeakerId`	INTEGER NOT NULL,
	PRIMARY KEY(`SeriesId`,`SpeakerId`)
);
CREATE TABLE `SERIES` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Theme`	TEXT NOT NULL,
	`Speaker`	INTEGER NOT NULL DEFAULT 0,
	`Venue`	INTEGER NOT NULL DEFAULT 0,
	`Town`	INTEGER NOT NULL DEFAULT 0,
	`Activity`	INTEGER NOT NULL DEFAULT 0,
	`StartDate`	TEXT NOT NULL,
	`EndDate`	TEXT NOT NULL
);
CREATE TABLE `RODs` (
	`DocId`	INTEGER NOT NULL,
	`DocTitle`	TEXT,
	PRIMARY KEY(`DocId`)
);
CREATE TABLE `PREFERENCES` (
	`PrinterName`	TEXT,
	`PrinterScheme`	TEXT DEFAULT 'White/Black',
	`ColourFont`	TEXT DEFAULT 'AACCFF',
	`ColourControls`	TEXT DEFAULT 222233,
	`FontSystem`	TEXT DEFAULT 'Times New Roman',
	`FontReader`	TEXT DEFAULT 'Times New Roman',
	`FontWriter`	TEXT DEFAULT 'Times New Roman',
	`RODMaxNumber`	INTEGER DEFAULT 10,
	`SortingFilter`	TEXT DEFAULT 'SPEAKER',
	`ShowWelcomeScreen`	TEXT DEFAULT 'True'
);
CREATE TABLE `ACTIVITIES` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE
);
COMMIT;

BEGIN TRANSACTION;
INSERT INTO `PREFERENCES` (
	PrinterName,
	PrinterScheme,
	ColourFont,
	ColourControls,
	FontSystem,
	FontReader,
	FontWriter,
	RODMaxNumber,
	SortingFilter,
	ShowWelcomeScreen) VALUES (
	'Microsoft XPS Document Writer',
	'',
	'170204255',
	'034034051',
	'Times New Roman',
	'Times New Roman',
	'Times New Roman',
	10,
	'Venue',
	'False');
COMMIT;

BEGIN TRANSACTION;
INSERT INTO `TOWNS` (Name) VALUES ('none');
INSERT INTO `TOWNS` (Name) VALUES ('Nairobi');
INSERT INTO `TOWNS` (Name) VALUES ('Mombasa');
INSERT INTO `TOWNS` (Name) VALUES ('Kisumu');
INSERT INTO `TOWNS` (Name) VALUES ('Nakuru');
INSERT INTO `TOWNS` (Name) VALUES ('Eldoret');
INSERT INTO `TOWNS` (Name) VALUES ('Kehancha');
INSERT INTO `TOWNS` (Name) VALUES ('Ruiru');
INSERT INTO `TOWNS` (Name) VALUES ('Kikuyu');
INSERT INTO `TOWNS` (Name) VALUES ('Kangundo-Tala');
INSERT INTO `TOWNS` (Name) VALUES ('Malindi');
INSERT INTO `TOWNS` (Name) VALUES ('Naivasha');
INSERT INTO `TOWNS` (Name) VALUES ('Kitui');
INSERT INTO `TOWNS` (Name) VALUES ('Machakos');
INSERT INTO `TOWNS` (Name) VALUES ('Thika');
INSERT INTO `TOWNS` (Name) VALUES ('Athi River (Mavoko)');
INSERT INTO `TOWNS` (Name) VALUES ('Karuri');
INSERT INTO `TOWNS` (Name) VALUES ('Nyeri');
INSERT INTO `TOWNS` (Name) VALUES ('Kilifi');
INSERT INTO `TOWNS` (Name) VALUES ('Garissa');
INSERT INTO `TOWNS` (Name) VALUES ('Vihiga');
INSERT INTO `TOWNS` (Name) VALUES ('Mumias');
INSERT INTO `TOWNS` (Name) VALUES ('Bomet');
INSERT INTO `TOWNS` (Name) VALUES ('Molo');
INSERT INTO `TOWNS` (Name) VALUES ('Ngong');
INSERT INTO `TOWNS` (Name) VALUES ('Kitale');
INSERT INTO `TOWNS` (Name) VALUES ('Litein');
INSERT INTO `TOWNS` (Name) VALUES ('Limuru');
INSERT INTO `TOWNS` (Name) VALUES ('Kericho');
INSERT INTO `TOWNS` (Name) VALUES ('Kimilili');
INSERT INTO `TOWNS` (Name) VALUES ('Awasi');
INSERT INTO `TOWNS` (Name) VALUES ('Kakamega');
INSERT INTO `TOWNS` (Name) VALUES ('Kapsabet');
INSERT INTO `TOWNS` (Name) VALUES ('Mariakani');
INSERT INTO `TOWNS` (Name) VALUES ('Kiambu');
INSERT INTO `TOWNS` (Name) VALUES ('Mandera');
INSERT INTO `TOWNS` (Name) VALUES ('Nyamira');
INSERT INTO `TOWNS` (Name) VALUES ('Mwingi');
INSERT INTO `TOWNS` (Name) VALUES ('Kisii');
INSERT INTO `TOWNS` (Name) VALUES ('Wajir');
INSERT INTO `TOWNS` (Name) VALUES ('Rongo');
INSERT INTO `TOWNS` (Name) VALUES ('Bungoma');
INSERT INTO `TOWNS` (Name) VALUES ('Ahero');
INSERT INTO `TOWNS` (Name) VALUES ('Nandi Hills');
INSERT INTO `TOWNS` (Name) VALUES ('Makuyu');
INSERT INTO `TOWNS` (Name) VALUES ('Kapenguria');
INSERT INTO `TOWNS` (Name) VALUES ('Taveta');
INSERT INTO `TOWNS` (Name) VALUES ('Narok');
INSERT INTO `TOWNS` (Name) VALUES ('Ol Kalou');
INSERT INTO `TOWNS` (Name) VALUES ('Kakuma');
INSERT INTO `TOWNS` (Name) VALUES ('Webuye');
INSERT INTO `TOWNS` (Name) VALUES ('Malaba');
INSERT INTO `TOWNS` (Name) VALUES ('Mbita Point');
INSERT INTO `TOWNS` (Name) VALUES ('Ukunda');
INSERT INTO `TOWNS` (Name) VALUES ('Wundanyi');
INSERT INTO `TOWNS` (Name) VALUES ('Busia');
INSERT INTO `TOWNS` (Name) VALUES ('Runyenjes');
INSERT INTO `TOWNS` (Name) VALUES ('Migori');
INSERT INTO `TOWNS` (Name) VALUES ('Malava');
INSERT INTO `TOWNS` (Name) VALUES ('Suneka');
INSERT INTO `TOWNS` (Name) VALUES ('Embu');
INSERT INTO `TOWNS` (Name) VALUES ('Ogembo');
INSERT INTO `TOWNS` (Name) VALUES ('Homa Bay');
INSERT INTO `TOWNS` (Name) VALUES ('Lodwar');
INSERT INTO `TOWNS` (Name) VALUES ('Kitengela');
INSERT INTO `TOWNS` (Name) VALUES ('Ukwala');
INSERT INTO `TOWNS` (Name) VALUES ('Keroka');
INSERT INTO `TOWNS` (Name) VALUES ('Meru');
INSERT INTO `TOWNS` (Name) VALUES ('Matuu');
INSERT INTO `TOWNS` (Name) VALUES ('Oyugis');
INSERT INTO `TOWNS` (Name) VALUES ('Nyahururu');
INSERT INTO `TOWNS` (Name) VALUES ('Kipkelion');
INSERT INTO `TOWNS` (Name) VALUES ('Luanda');
INSERT INTO `TOWNS` (Name) VALUES ('Nanyuki');
INSERT INTO `TOWNS` (Name) VALUES ('Maua');
INSERT INTO `TOWNS` (Name) VALUES ('Mtwapa');
INSERT INTO `TOWNS` (Name) VALUES ('Isiolo');
INSERT INTO `TOWNS` (Name) VALUES ('Eldama Ravine');
INSERT INTO `TOWNS` (Name) VALUES ('Voi');
INSERT INTO `TOWNS` (Name) VALUES ('Siaya');
INSERT INTO `TOWNS` (Name) VALUES ('Nyansiongo');
INSERT INTO `TOWNS` (Name) VALUES ('Londiani');
INSERT INTO `TOWNS` (Name) VALUES ('Iten/Tambach');
INSERT INTO `TOWNS` (Name) VALUES ('Chuka');
INSERT INTO `TOWNS` (Name) VALUES ('Malakisi');
INSERT INTO `TOWNS` (Name) VALUES ('Juja');
INSERT INTO `TOWNS` (Name) VALUES ('Ongata Rongai');
INSERT INTO `TOWNS` (Name) VALUES ('Bondo');
INSERT INTO `TOWNS` (Name) VALUES ('Moyale');
INSERT INTO `TOWNS` (Name) VALUES ('Maralal');
INSERT INTO `TOWNS` (Name) VALUES ('Gilgil');
INSERT INTO `TOWNS` (Name) VALUES ('Nambale');
INSERT INTO `TOWNS` (Name) VALUES ('Tabaka');
INSERT INTO `TOWNS` (Name) VALUES ('Muhoroni');
INSERT INTO `TOWNS` (Name) VALUES ('Kerugoya/Kutus');
INSERT INTO `TOWNS` (Name) VALUES ('Ugunja');
INSERT INTO `TOWNS` (Name) VALUES ('Yala');
INSERT INTO `TOWNS` (Name) VALUES ('Rumuruti');
INSERT INTO `TOWNS` (Name) VALUES ('Burnt Forest');
INSERT INTO `TOWNS` (Name) VALUES ('Maragua');
INSERT INTO `TOWNS` (Name) VALUES ('Kendu Bay');
INSERT INTO `TOWNS` (Name) VALUES ('Archerspost');
INSERT INTO `TOWNS` (Name) VALUES ('Bahati');
INSERT INTO `TOWNS` (Name) VALUES ('Baragoi');
INSERT INTO `TOWNS` (Name) VALUES ('Baringo');
INSERT INTO `TOWNS` (Name) VALUES ('Bissil');
INSERT INTO `TOWNS` (Name) VALUES ('Bumala');
INSERT INTO `TOWNS` (Name) VALUES ('Butere');
INSERT INTO `TOWNS` (Name) VALUES ('Cheptais');
INSERT INTO `TOWNS` (Name) VALUES ('Chogoria');
INSERT INTO `TOWNS` (Name) VALUES ('Daadab');
INSERT INTO `TOWNS` (Name) VALUES ('Dundori');
INSERT INTO `TOWNS` (Name) VALUES ('Endarasha');
INSERT INTO `TOWNS` (Name) VALUES ('Funyula');
INSERT INTO `TOWNS` (Name) VALUES ('Garbatula');
INSERT INTO `TOWNS` (Name) VALUES ('Gatundu');
INSERT INTO `TOWNS` (Name) VALUES ('Hola');
INSERT INTO `TOWNS` (Name) VALUES ('Iten');
INSERT INTO `TOWNS` (Name) VALUES ('Juakali');
INSERT INTO `TOWNS` (Name) VALUES ('Kabarnet');
INSERT INTO `TOWNS` (Name) VALUES ('Kabati');
INSERT INTO `TOWNS` (Name) VALUES ('Kabuti');
INSERT INTO `TOWNS` (Name) VALUES ('Kagio');
INSERT INTO `TOWNS` (Name) VALUES ('Kagumo');
INSERT INTO `TOWNS` (Name) VALUES ('Kajiado');
INSERT INTO `TOWNS` (Name) VALUES ('Kaloleni');
INSERT INTO `TOWNS` (Name) VALUES ('Kandara');
INSERT INTO `TOWNS` (Name) VALUES ('Kangari');
INSERT INTO `TOWNS` (Name) VALUES ('Kangema');
INSERT INTO `TOWNS` (Name) VALUES ('Kangundo');
INSERT INTO `TOWNS` (Name) VALUES ('Kapcherop');
INSERT INTO `TOWNS` (Name) VALUES ('Kapsokwony');
INSERT INTO `TOWNS` (Name) VALUES ('Kapsowar');
INSERT INTO `TOWNS` (Name) VALUES ('Karatina');
INSERT INTO `TOWNS` (Name) VALUES ('Kathiani');
INSERT INTO `TOWNS` (Name) VALUES ('Kibwezi');
INSERT INTO `TOWNS` (Name) VALUES ('Kinamba');
INSERT INTO `TOWNS` (Name) VALUES ('Kinna');
INSERT INTO `TOWNS` (Name) VALUES ('Kiria-Ini');
INSERT INTO `TOWNS` (Name) VALUES ('Laisamis');
INSERT INTO `TOWNS` (Name) VALUES ('Lamu');
INSERT INTO `TOWNS` (Name) VALUES ('Lare');
INSERT INTO `TOWNS` (Name) VALUES ('Loiyangalani');
INSERT INTO `TOWNS` (Name) VALUES ('Lokichogio');
INSERT INTO `TOWNS` (Name) VALUES ('Lolgorian');
INSERT INTO `TOWNS` (Name) VALUES ('Lungalunga');
INSERT INTO `TOWNS` (Name) VALUES ('Machinery');
INSERT INTO `TOWNS` (Name) VALUES ('Magarini');
INSERT INTO `TOWNS` (Name) VALUES ('Majimazuri');
INSERT INTO `TOWNS` (Name) VALUES ('Marereni');
INSERT INTO `TOWNS` (Name) VALUES ('Maseno');
INSERT INTO `TOWNS` (Name) VALUES ('Masii');
INSERT INTO `TOWNS` (Name) VALUES ('Maunarok');
INSERT INTO `TOWNS` (Name) VALUES ('Mazeras');
INSERT INTO `TOWNS` (Name) VALUES ('Merti');
INSERT INTO `TOWNS` (Name) VALUES ('Mitunguu');
INSERT INTO `TOWNS` (Name) VALUES ('Mogonga');
INSERT INTO `TOWNS` (Name) VALUES ('Mogotio');
INSERT INTO `TOWNS` (Name) VALUES ('Mtito Andei');
INSERT INTO `TOWNS` (Name) VALUES ('Muhuru Bay');
INSERT INTO `TOWNS` (Name) VALUES ('Muranga');
INSERT INTO `TOWNS` (Name) VALUES ('Mwatate');
INSERT INTO `TOWNS` (Name) VALUES ('Mweiga');
INSERT INTO `TOWNS` (Name) VALUES ('Nairagieenkare');
INSERT INTO `TOWNS` (Name) VALUES ('Naromoru');
INSERT INTO `TOWNS` (Name) VALUES ('Ndori');
INSERT INTO `TOWNS` (Name) VALUES ('Ngong’');
INSERT INTO `TOWNS` (Name) VALUES ('Njabini');
INSERT INTO `TOWNS` (Name) VALUES ('Nyakach');
INSERT INTO `TOWNS` (Name) VALUES ('Nyamache');
INSERT INTO `TOWNS` (Name) VALUES ('Nyamarambe');
INSERT INTO `TOWNS` (Name) VALUES ('Olenguruone');
INSERT INTO `TOWNS` (Name) VALUES ('Othaya');
INSERT INTO `TOWNS` (Name) VALUES ('Rongai');
INSERT INTO `TOWNS` (Name) VALUES ('Salgaa');
INSERT INTO `TOWNS` (Name) VALUES ('Siakago');
INSERT INTO `TOWNS` (Name) VALUES ('Sindo');
INSERT INTO `TOWNS` (Name) VALUES ('Sololo');
INSERT INTO `TOWNS` (Name) VALUES ('Sultan Hamud');
INSERT INTO `TOWNS` (Name) VALUES ('Timboroa');
INSERT INTO `TOWNS` (Name) VALUES ('Tongaren');
INSERT INTO `TOWNS` (Name) VALUES ('Watamu');
INSERT INTO `TOWNS` (Name) VALUES ('Wote');
INSERT INTO `TOWNS` (Name) VALUES ('Kahawa');
COMMIT;
